@file:Suppress("unused")

package com.gazim.app.exchange_rates.ui.model

enum class ExchangeFlag(val flagResName: String, vararg exchanges: String) {
    Australia("au.svg", "AUD"),
    Azerbaijan("az.svg", "AZN"),
    UK("gb.svg", "GBP"),
    Armenia("am.svg", "AMD"),
    Belarus("by.svg", "BYN", "BYR", "BYB"),
    Bulgaria("bg.svg", "BGN"),
    Brazil("br.svg", "BRL"),
    Hungary("hu.svg", "HUF"),
    Vietnam("vn.svg", "VND"),
    HongKong("hk.svg", "HKD"),
    Georgia("ge.svg", "GEL"),
    Denmark("dk.svg", "DKK"),
    UAE("ae.svg", "AED"),
    US("us.svg", "USD"),
    Europe("eu.svg", "EUR"),
    Egypt("eg.svg", "EGP"),
    India("in.svg", "INR"),
    Indonesia("id.svg", "IDR"),
    Kazakhstan("kz.svg", "KZT"),
    Canada("ca.svg", "CAD"),
    Qatar("qa.svg", "QAR"),
    Kyrgyzstan("kg.svg", "KGS"),
    China("cn.svg", "CNY"),
    Moldova("md.svg", "MDL"),
    NewZealand("nz.svg", "NZD"),
    Norway("no.svg", "NOK"),
    Poland("pl.svg", "PLN"),
    Romania("ro.svg", "RON"),
    InternationalMonetaryFund("imf.svg", "XDR"),
    Singapore("sg.svg", "SGD"),
    Tajikistan("tj.svg", "TJS"),
    Thailand("th.svg", "THB"),
    Turkey("tr.svg", "TRY", "TRL"),
    Turkmenistan("tm.svg", "TMT"),
    Uzbekistan("uz.svg", "UZS"),
    Ukraine("ua.svg", "UAH"),
    CzechRepublic("cz.svg", "CZK"),
    Sweden("se.svg", "SEK"),
    Switzerland("ch.svg", "CHF"),
    Serbia("rs.svg", "RSD"),
    SouthAfrica("za.svg", "ZAR"),
    SouthKorea("kr.svg", "KRW"),
    Japan("jp.svg", "JPY"),
    Iceland("is.svg", "ISK"),
    Latvia("lv.svg", "LVL"),
    Lithuania("lt.svg", "LTL"),
    Austria("at.svg", "ATS"),
    Belgium("be.svg", "BEF"),
    Greece("gr.svg", "GRD"),
    Ireland("ie.svg", "IEP"),
    Spain("es.svg", "ESP"),
    Italy("it.svg", "ITL"),
    Germany("de.svg", "DEM"),
    Netherlands("nl.svg", "NLG"),
    Portugal("pt.svg", "PTE"),
    Finland("fi.svg", "FIM"),
    France("fr.svg", "FRF"),
    EuropeanCurrencyUnit("ecu.svg", "XEU");

    val exchanges = exchanges.toList()
    val flagsResFolder = "flags"
    fun getPath(aspectRatio: AspectRatio) = "$flagsResFolder/${aspectRatio.ratioStr}/$flagResName"
}

