package com.gazim.app.exchange_rates.ui.model

enum class ExchangeFlag(val exchange: String, val flagResName: String) {
    Australia("AUD", "au.svg"),
    Azerbaijan("AZN", "az.svg"),
    UK("GBP", "gb.svg"),
    Armenia("AMD", "am.svg"),
    Belarus("BYN", "by.svg"),
    OldBelarus("BYR", "by.svg"),
    Bulgaria("BGN", "bg.svg"),
    Brazil("BRL", "br.svg"),
    Hungary("HUF", "hu.svg"),
    Vietnam("VND", "vn.svg"),
    HongKong("HKD", "hk.svg"),
    Georgia("GEL", "ge.svg"),
    Denmark("DKK", "dk.svg"),
    UAE("AED", "ae.svg"),
    US("USD", "us.svg"),
    Europe("EUR", "eu.svg"),
    Egypt("EGP", "eg.svg"),
    India("INR", "in.svg"),
    Indonesia("IDR", "id.svg"),
    Kazakhstan("KZT", "kz.svg"),
    Canada("CAD", "ca.svg"),
    Qatar("QAR", "qa.svg"),
    Kyrgyzstan("KGS", "kg.svg"),
    China("CNY", "cn.svg"),
    Moldova("MDL", "md.svg"),
    NewZealand("NZD", "nz.svg"),
    Norway("NOK", "no.svg"),
    Poland("PLN", "pl.svg"),
    Romania("RON", "ro.svg"),
    InternationalMonetaryFund("XDR", "imf.svg"),
    Singapore("SGD", "sg.svg"),
    Tajikistan("TJS", "tj.svg"),
    Thailand("THB", "th.svg"),
    Turkey("TRY", "tr.svg"),
    Turkmenistan("TMT", "tm.svg"),
    Uzbekistan("UZS", "uz.svg"),
    Ukraine("UAH", "ua.svg"),
    CzechRepublic("CZK", "cz.svg"),
    Sweden("SEK", "se.svg"),
    Switzerland("CHF", "ch.svg"),
    Serbia("RSD", "rs.svg"),
    SouthAfrica("ZAR", "za.svg"),
    SouthKorea("KRW", "kr.svg"),
    Japan("JPY", "jp.svg"),
    Iceland("ISK", "is.svg"),
    Latvia("LVL", "lv.svg"),
    Lithuania("LTL", "lt.svg"),
    Austria("ATS", "at.svg"),
    Belgium("BEF", "be.svg"),
    Greece("GRD", "gr.svg"),
    Ireland("IEP", "ie.svg"),
    Spain("ESP", "es.svg"),
    Italy("ITL", "it.svg"),
    Germany("DEM", "de.svg"),
    Netherlands("NLG", "nl.svg"),
    Portugal("PTE", "pt.svg"),
    OldTurkey("TRL", "tr.svg"),
    Finland("FIM", "fi.svg"),
    France("FRF", "fr.svg");

    val flagsResFolder = "flags"
    fun getPath(aspectRatio: AspectRatio) = "$flagsResFolder/${aspectRatio.ratio}/$flagResName"
}

